import { Product } from "./productCard";

export const shopProducts: Product[] = [
  {
    id: "1",
    name: "Pyar Embroidered Straight Short Kurti",
    slug: "pyar-embroidered-straight-short-kurti",
    isFeatured: true,
    isTrending: true,
    price: 950.0,
    originalPrice: 1299.0,
    images: [
      "https://images.pexels.com/photos/28512787/pexels-photo-28512787.jpeg",
      "https://images.pexels.com/photos/28512779/pexels-photo-28512779.jpeg",
      "https://images.pexels.com/photos/35521738/pexels-photo-35521738.jpeg",
      "https://images.pexels.com/photos/28512781/pexels-photo-28512781.jpeg"
    ],
    rating: 4.8,
    reviews: 124,
    tags: ["Best Seller", "New"],
    category: "clothing",
    shortDescription:
      "Elegant embroidered kurti perfect for casual and festive occasions. Made with premium cotton fabric for ultimate comfort.",
    description:
      "Introducing our stunning Pyar Embroidered Straight Short Kurti, a perfect blend of traditional craftsmanship and contemporary style. This beautiful kurti features intricate embroidery work that showcases the rich heritage of Indian textile artistry. The straight-cut silhouette offers a flattering fit for all body types, while the short length makes it versatile enough to pair with jeans, palazzos, or traditional bottoms.\n\nCrafted from premium quality cotton fabric, this kurti ensures breathability and comfort throughout the day. The soft texture feels gentle against the skin, making it ideal for long hours of wear. Whether you're heading to the office, attending a casual gathering, or celebrating a festive occasion, this kurti will keep you looking effortlessly elegant.",
    features: [
      "Hand-embroidered intricate patterns",
      "Premium 100% cotton fabric",
      "Comfortable straight-cut fit",
      "Versatile short length",
      "Easy to wash and maintain",
      "Fade-resistant colors",
      "Breathable fabric for all-day comfort",
    ],
    specifications: [
      { label: "Fabric", value: "100% Cotton" },
      { label: "Pattern", value: "Embroidered" },
      { label: "Sleeve Type", value: "3/4th Sleeves" },
      { label: "Neck Type", value: "Round Neck" },
      { label: "Hem Length", value: "Short/Hip Length" },
      { label: "Fit Type", value: "Regular Fit" },
      { label: "Occasion", value: "Casual, Festive, Office Wear" },
      { label: "Wash Care", value: "Machine Washable" },
    ],
    careInstructions: [
      "Machine wash cold with similar colors",
      "Do not bleach",
      "Tumble dry low",
      "Iron on medium heat",
      "Do not dry clean",
    ],
    material: "100% Premium Cotton",
    color: "Red with White Embroidery",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 45,
    sku: "PESS-KRT-001",
    brand: "Softzy",
    weight: "250g",
    dimensions: "Varies by size",
    warranty: "30-day quality guarantee",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/pyar-embroidered-kurti",
  },
  {
    id: "2",
    name: "Floral Print Cotton Anarkali Kurti",
    slug: "floral-print-cotton-anarkali-kurti",
    isMustTry: true,
    isTrending: true,
    price: 1250.0,
    originalPrice: 1599.0,
    images: [
      "https://images.pexels.com/photos/28390547/pexels-photo-28390547.jpeg",
      "https://images.pexels.com/photos/28512779/pexels-photo-28512779.jpeg",
      "https://images.pexels.com/photos/35521738/pexels-photo-35521738.jpeg",
      "https://images.pexels.com/photos/28512781/pexels-photo-28512781.jpeg"
    ],
    rating: 4.6,
    reviews: 89,
    tags: ["Trending"],
    category: "clothing",
    shortDescription:
      "Beautiful floral print Anarkali kurti with a flowing silhouette. Perfect for festive occasions and celebrations.",
    description:
      "Step into elegance with our Floral Print Cotton Anarkali Kurti. This stunning piece features a gorgeous floral print that captures the essence of nature's beauty. The classic Anarkali silhouette flows gracefully, creating a regal and feminine look that's perfect for special occasions.\n\nMade from breathable cotton fabric, this kurti keeps you comfortable while looking absolutely stunning. The vibrant floral patterns are printed using eco-friendly dyes that are gentle on your skin and the environment.",
    features: [
      "Beautiful floral print design",
      "Classic Anarkali silhouette",
      "Breathable cotton fabric",
      "Eco-friendly dyes",
      "Elegant flared bottom",
      "Perfect for festive wear",
    ],
    specifications: [
      { label: "Fabric", value: "Cotton" },
      { label: "Pattern", value: "Floral Print" },
      { label: "Style", value: "Anarkali" },
      { label: "Sleeve Type", value: "Full Sleeves" },
      { label: "Occasion", value: "Festive, Party Wear" },
    ],
    careInstructions: [
      "Hand wash recommended",
      "Wash separately first time",
      "Do not bleach",
      "Dry in shade",
    ],
    material: "Cotton",
    color: "Multi-color Floral",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    stockCount: 32,
    sku: "FPC-ANK-002",
    brand: "Softzy",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/floral-anarkali",
  },
  {
    id: "3",
    name: "Designer Chikankari Kurti",
    slug: "designer-chikankari-kurti",
    isFeatured: true,
    isMustTry: true,
    price: 1450.0,
    images: [
      "https://images.pexels.com/photos/19556879/pexels-photo-19556879.jpeg",
    ],
    rating: 4.9,
    reviews: 156,
    tags: ["New"],
    category: "clothing",
    shortDescription:
      "Authentic Lucknowi Chikankari hand-embroidered kurti. A masterpiece of traditional Indian craftsmanship.",
    description:
      "Experience the timeless elegance of Lucknowi Chikankari with our Designer Chikankari Kurti. Each piece is meticulously hand-embroidered by skilled artisans who have inherited this beautiful craft through generations. The delicate threadwork creates intricate patterns that are both subtle and stunning.\n\nThis kurti represents the finest traditions of Indian handloom industry. The lightweight fabric combined with the exquisite embroidery makes it perfect for both casual outings and formal occasions.",
    features: [
      "Authentic Lucknowi Chikankari",
      "100% hand-embroidered",
      "Lightweight and comfortable",
      "Artisan crafted",
      "Timeless design",
      "Premium quality fabric",
    ],
    specifications: [
      { label: "Fabric", value: "Cotton Cambric" },
      { label: "Embroidery", value: "Chikankari Hand Embroidery" },
      { label: "Origin", value: "Lucknow, India" },
      { label: "Craft Type", value: "Traditional Handloom" },
    ],
    material: "Cotton Cambric",
    color: "White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 18,
    sku: "DCK-CHK-003",
    brand: "Softzy",
    warranty: "Authenticity guaranteed",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/chikankari-kurti",
  },
  {
    id: "4",
    name: "Gold Plated Kundan Necklace Set",
    slug: "gold-plated-kundan-necklace-set",
    isFeatured: true,
    isTrending: true,
    price: 2499.0,
    originalPrice: 3499.0,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
      "https://images.pexels.com/photos/17298688/pexels-photo-17298688.jpeg"
    ],
    rating: 4.7,
    reviews: 203,
    tags: ["Best Seller"],
    category: "jewelry",
    shortDescription:
      "Exquisite gold-plated Kundan necklace set with matching earrings. Perfect for weddings and special occasions.",
    description:
      "Adorn yourself with the magnificence of our Gold Plated Kundan Necklace Set. This stunning jewelry set features authentic Kundan work, a traditional Indian jewelry-making technique that has been practiced for centuries. The intricate setting of polished glass stones creates a mesmerizing sparkle that catches light beautifully.\n\nThe set includes a statement necklace and matching earrings, creating a complete look for your special occasions. Whether it's a wedding, engagement, or festive celebration, this jewelry set will make you the center of attention.\n\nCrafted with high-quality materials and finished with premium gold plating, this set offers the luxurious look of fine jewelry at an accessible price point.",
    features: [
      "Authentic Kundan craftsmanship",
      "Premium gold plating",
      "Includes necklace and earrings",
      "Hypoallergenic materials",
      "Secure clasps",
      "Elegant presentation box included",
      "Suitable for sensitive skin",
    ],
    specifications: [
      { label: "Material", value: "Brass with Gold Plating" },
      { label: "Stone Type", value: "Kundan (Polished Glass)" },
      { label: "Plating", value: "22K Gold Plated" },
      { label: "Necklace Length", value: "18 inches with 2 inch extender" },
      { label: "Earring Type", value: "Jhumka Style" },
      { label: "Closure", value: "Lobster Clasp" },
      { label: "Set Includes", value: "1 Necklace, 1 Pair Earrings" },
    ],
    careInstructions: [
      "Store in jewelry box when not wearing",
      "Avoid contact with water and perfume",
      "Clean with soft dry cloth",
      "Remove before sleeping or bathing",
    ],
    material: "Brass with 22K Gold Plating",
    color: "Gold with Multi-color Stones",
    inStock: true,
    stockCount: 25,
    sku: "GPK-NKL-004",
    brand: "Softzy Jewels",
    weight: "85g",
    warranty: "6 months plating warranty",
    returnPolicy: "Easy 7-day returns (unworn items)",
    buyLink: "https://example.com/buy/kundan-necklace-set",
  },
  {
    id: "5",
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    isMustTry: true,
    price: 599.0,
    originalPrice: 899.0,
    images: [
      "https://plus.unsplash.com/premium_photo-1681276170281-cf50a487a1b7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZWFyaW5nc3xlbnwwfHwwfHx8MA%3D%3D",
      "https://images.unsplash.com/photo-1714733831162-0a6e849141be?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGVhcmluZ3N8ZW58MHx8MHx8fDA%3D",
      "https://images.unsplash.com/photo-1648291531524-97afa1c2ac30?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGVhcmluZ3N8ZW58MHx8MHx8fDA%3D"
    ],
    rating: 4.5,
    reviews: 78,
    tags: ["Sale"],
    category: "jewelry",
    shortDescription:
      "Elegant pearl drop earrings that add a touch of sophistication to any outfit. Classic design for everyday luxury.",
    description:
      "Embrace timeless elegance with our Pearl Drop Earrings. These beautifully crafted earrings feature lustrous freshwater pearls that hang gracefully, catching the light with every movement. The classic drop design is both versatile and sophisticated, making these earrings perfect for any occasion.\n\nWhether you're dressing up for a formal event or adding a touch of refinement to your everyday look, these pearl earrings will become your go-to accessory. The high-quality sterling silver posts are hypoallergenic, ensuring comfortable wear even for sensitive ears.",
    features: [
      "Genuine freshwater pearls",
      "Sterling silver posts",
      "Hypoallergenic",
      "Lightweight and comfortable",
      "Versatile design",
      "Gift box included",
    ],
    specifications: [
      { label: "Pearl Type", value: "Freshwater Pearl" },
      { label: "Pearl Size", value: "8-9mm" },
      { label: "Post Material", value: "925 Sterling Silver" },
      { label: "Drop Length", value: "1.5 inches" },
      { label: "Backing Type", value: "Push Back" },
    ],
    careInstructions: [
      "Wipe with soft cloth after wearing",
      "Store separately from other jewelry",
      "Avoid contact with chemicals",
      "Put on after applying makeup and perfume",
    ],
    material: "Freshwater Pearl, Sterling Silver",
    color: "White Pearl / Silver",
    inStock: true,
    stockCount: 56,
    sku: "PDE-EAR-005",
    brand: "Softzy Jewels",
    weight: "8g",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/pearl-drop-earrings",
  },
  {
    id: "6",
    name: "Handcrafted Brass Diya Set",
    slug: "handcrafted-brass-diya-set",
    isFeatured: true,
    isTrending: true,
    price: 899.0,
    images: [
      "https://images.pexels.com/photos/31104752/pexels-photo-31104752.jpeg",
      "https://images.pexels.com/photos/8887005/pexels-photo-8887005.jpeg"
    ],
    rating: 4.9,
    reviews: 56,
    tags: ["Trending"],
    category: "home-decor",
    shortDescription:
      "Traditional handcrafted brass diya set for pooja and home decoration. Set of 5 beautiful diyas with intricate designs.",
    description:
      "Illuminate your home with divine radiance using our Handcrafted Brass Diya Set. This exquisite set of 5 diyas is lovingly handcrafted by skilled artisans using traditional techniques passed down through generations. Each diya features intricate engravings and patterns that reflect India's rich cultural heritage.\n\nPerfect for daily pooja, festivals like Diwali, or simply as decorative pieces, these brass diyas add warmth and spirituality to any space. The high-quality brass ensures durability and develops a beautiful patina over time, making each piece uniquely yours.\n\nThese diyas are not just functional items but works of art that celebrate the craftsmanship of Indian artisans.",
    features: [
      "100% handcrafted by skilled artisans",
      "Premium quality brass",
      "Set of 5 diyas in varying sizes",
      "Intricate traditional engravings",
      "Durable and long-lasting",
      "Develops beautiful patina over time",
      "Suitable for oil or ghee",
    ],
    specifications: [
      { label: "Material", value: "Pure Brass" },
      { label: "Set Contains", value: "5 Diyas" },
      { label: "Sizes", value: "2 inch, 2.5 inch, 3 inch, 3.5 inch, 4 inch" },
      { label: "Craft", value: "Hand Engraved" },
      { label: "Finish", value: "Antique Brass" },
      { label: "Weight (Total)", value: "450g" },
    ],
    careInstructions: [
      "Clean with brass cleaner or lemon and salt",
      "Wipe dry after cleaning",
      "Store in dry place",
      "Handle with care to preserve engravings",
    ],
    material: "Pure Brass",
    color: "Antique Brass",
    inStock: true,
    stockCount: 38,
    sku: "HBD-SET-006",
    brand: "Softzy Home",
    weight: "450g",
    dimensions: "Various sizes (2-4 inch diameter)",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/brass-diya-set",
  },
  {
    id: "7",
    name: "Macrame Wall Hanging",
    slug: "macrame-wall-hanging",
    isMustTry: true,
    isTrending: true,
    price: 1299.0,
    images: [
      "https://images.unsplash.com/photo-1745954757871-3be53100bad7?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1641260184678-2922bd1ae301?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    ],
    rating: 4.6,
    reviews: 34,
    tags: ["New"],
    category: "home-decor",
    shortDescription:
      "Beautiful handmade macrame wall hanging. Adds bohemian charm and texture to any room.",
    description:
      "Transform your walls with our stunning Macrame Wall Hanging. This beautiful piece is entirely handcrafted using the ancient art of macrame, where cords are knotted together to create intricate patterns. Each wall hanging is a unique work of art, made with love and attention to detail.\n\nThe bohemian-inspired design adds texture, warmth, and visual interest to any space. Whether hung in your living room, bedroom, or even outdoors, this macrame piece creates a focal point that guests will admire.\n\nMade from 100% natural cotton cord, this wall hanging is eco-friendly and sustainable, aligning with conscious living values.",
    features: [
      "100% handmade macrame",
      "Natural cotton cord",
      "Bohemian design",
      "Easy to hang",
      "Eco-friendly materials",
      "Unique artisan piece",
      "Includes wooden dowel",
    ],
    specifications: [
      { label: "Material", value: "100% Cotton Cord" },
      { label: "Dimensions", value: "24 inches wide x 36 inches long" },
      { label: "Hanging Method", value: "Wooden Dowel" },
      { label: "Style", value: "Bohemian / Boho" },
      { label: "Color", value: "Natural Cream" },
    ],
    careInstructions: [
      "Dust gently with soft brush",
      "Spot clean if necessary",
      "Keep away from direct sunlight to prevent yellowing",
      "Reshape tassels gently if needed",
    ],
    material: "100% Natural Cotton",
    color: "Natural Cream",
    inStock: true,
    stockCount: 22,
    sku: "MWH-DEC-007",
    brand: "Softzy Home",
    weight: "350g",
    dimensions: "24 x 36 inches",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/macrame-wall-hanging",
  },
  {
    id: "8",
    name: "Organic Rose Face Serum",
    slug: "organic-rose-face-serum",
    isFeatured: true,
    isTrending: true,
    isMustTry: true,
    price: 649.0,
    originalPrice: 899.0,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviews: 203,
    tags: ["Best Seller"],
    category: "beauty",
    shortDescription:
      "Luxurious organic face serum with pure rose extracts. Hydrates, nourishes, and gives you a natural glow.",
    description:
      "Reveal your skin's natural radiance with our Organic Rose Face Serum. This luxurious serum is crafted with pure rose extracts and a blend of organic botanical oils that work together to deeply nourish and hydrate your skin. The lightweight formula absorbs quickly, leaving your skin soft, supple, and glowing.\n\nRoses have been celebrated for centuries for their skincare benefits, and our serum captures these benefits in every drop. Rich in antioxidants and vitamins, this serum helps combat signs of aging while providing intense hydration.\n\nFree from harsh chemicals, parabens, and artificial fragrances, this serum is gentle enough for all skin types, including sensitive skin.",
    features: [
      "100% organic ingredients",
      "Pure rose extract",
      "Lightweight, fast-absorbing",
      "Suitable for all skin types",
      "Paraben-free and cruelty-free",
      "No artificial fragrances",
      "Antioxidant-rich formula",
      "Visible results in 2 weeks",
    ],
    specifications: [
      { label: "Volume", value: "30ml" },
      {
        label: "Key Ingredients",
        value: "Rose Extract, Rosehip Oil, Vitamin E",
      },
      { label: "Skin Type", value: "All Skin Types" },
      { label: "Texture", value: "Lightweight Serum" },
      { label: "Certification", value: "Organic Certified" },
      { label: "Shelf Life", value: "24 months (unopened)" },
    ],
    careInstructions: [
      "Apply 2-3 drops on clean, damp skin",
      "Use morning and night for best results",
      "Follow with moisturizer",
      "Store in cool, dry place away from sunlight",
    ],
    material: "Organic Rose Extract, Natural Oils",
    inStock: true,
    stockCount: 89,
    sku: "ORF-SER-008",
    brand: "Softzy Beauty",
    weight: "50g (with packaging)",
    warranty: "Satisfaction guaranteed",
    returnPolicy: "Unopened items returnable within 7 days",
    buyLink: "https://example.com/buy/rose-face-serum",
  },
  {
    id: "9",
    name: "Ayurvedic Hair Oil",
    slug: "ayurvedic-hair-oil",
    isMustTry: true,
    isTrending: true,
    price: 449.0,
    originalPrice: 599.0,
    images: [
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviews: 167,
    tags: ["Sale"],
    category: "beauty",
    shortDescription:
      "Traditional Ayurvedic hair oil with 21 herbs. Promotes hair growth, reduces hair fall, and nourishes scalp.",
    description:
      "Revitalize your hair with our traditional Ayurvedic Hair Oil, formulated with a powerful blend of 21 herbs known for their hair-nourishing properties. This time-tested formula combines ancient Ayurvedic wisdom with modern quality standards to deliver an oil that truly transforms your hair.\n\nThe carefully selected herbs including Bhringraj, Amla, Brahmi, and Coconut Oil work synergistically to strengthen hair roots, reduce hair fall, promote new hair growth, and add natural shine. Regular use helps address common hair concerns while keeping your scalp healthy.\n\nOur oil is cold-pressed to preserve the natural nutrients and is free from mineral oils, parabens, and artificial additives.",
    features: [
      "21 Ayurvedic herbs blend",
      "Promotes hair growth",
      "Reduces hair fall",
      "Nourishes scalp",
      "Cold-pressed extraction",
      "No mineral oil or parabens",
      "Traditional formulation",
      "Pleasant herbal fragrance",
    ],
    specifications: [
      { label: "Volume", value: "200ml" },
      { label: "Key Herbs", value: "Bhringraj, Amla, Brahmi, Coconut Oil" },
      { label: "Hair Type", value: "All Hair Types" },
      { label: "Extraction", value: "Cold Pressed" },
      { label: "Shelf Life", value: "36 months" },
    ],
    careInstructions: [
      "Massage gently into scalp and hair",
      "Leave for at least 1 hour or overnight",
      "Wash with mild shampoo",
      "Use 2-3 times per week for best results",
    ],
    material: "Natural Ayurvedic Herbs & Oils",
    inStock: true,
    stockCount: 134,
    sku: "AYU-OIL-009",
    brand: "Softzy Beauty",
    weight: "220g",
    returnPolicy: "Unopened items returnable within 7 days",
    buyLink: "https://example.com/buy/ayurvedic-hair-oil",
  },
  {
    id: "10",
    name: "Leather Tote Bag",
    slug: "leather-tote-bag",
    isFeatured: true,
    isTrending: true,
    price: 1999.0,
    originalPrice: 2799.0,
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviews: 67,
    tags: ["Trending"],
    category: "bags",
    shortDescription:
      "Premium leather tote bag with spacious interior. Perfect for work, travel, or everyday use.",
    description:
      "Elevate your everyday style with our Premium Leather Tote Bag. Crafted from genuine full-grain leather, this tote combines timeless elegance with practical functionality. The spacious interior easily accommodates your laptop, documents, and daily essentials, making it perfect for the modern professional.\n\nThe bag features multiple interior pockets for organization, reinforced stitching for durability, and comfortable leather handles that soften with use. The leather develops a beautiful patina over time, making each bag uniquely yours.\n\nWhether you're heading to the office, traveling, or running errands, this versatile tote bag transitions seamlessly from professional to casual settings.",
    features: [
      "Genuine full-grain leather",
      "Spacious main compartment",
      "Fits 15-inch laptop",
      "Multiple interior pockets",
      "Reinforced stitching",
      "Magnetic snap closure",
      "Comfortable carry handles",
      "Develops patina over time",
    ],
    specifications: [
      { label: "Material", value: "Full-Grain Leather" },
      { label: "Dimensions", value: "16 x 12 x 5 inches" },
      { label: "Strap Drop", value: "10 inches" },
      { label: "Closure", value: "Magnetic Snap" },
      { label: "Interior", value: "Cotton Lining" },
      { label: "Pockets", value: "2 Interior, 1 Zipper" },
    ],
    careInstructions: [
      "Wipe with damp cloth for regular cleaning",
      "Use leather conditioner every 3-6 months",
      "Store stuffed to maintain shape",
      "Keep away from direct heat and sunlight",
    ],
    material: "Full-Grain Leather",
    color: "Tan Brown",
    inStock: true,
    stockCount: 28,
    sku: "LTB-BAG-010",
    brand: "Softzy",
    weight: "850g",
    dimensions: "16 x 12 x 5 inches",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/leather-tote-bag",
  },
  {
    id: "11",
    name: "Handmade Jute Clutch",
    slug: "handmade-jute-clutch",
    isMustTry: true,
    price: 499.0,
    images: [
      "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.3,
    reviews: 45,
    tags: ["New"],
    category: "bags",
    shortDescription:
      "Eco-friendly handmade jute clutch with traditional embroidery. Sustainable fashion at its best.",
    description:
      "Make a sustainable style statement with our Handmade Jute Clutch. This eco-friendly clutch is crafted from natural jute fiber and adorned with beautiful traditional embroidery, showcasing the skill of Indian artisans. The perfect blend of sustainability and style, this clutch proves that fashion can be both beautiful and responsible.\n\nThe compact size is ideal for carrying your essentials – phone, cards, keys, and makeup touch-ups. The secure magnetic closure keeps your belongings safe, while the detachable wrist strap offers versatile carrying options.\n\nEach clutch is unique, with slight variations in embroidery that make it truly one-of-a-kind.",
    features: [
      "100% natural jute fiber",
      "Handmade with traditional embroidery",
      "Eco-friendly and sustainable",
      "Detachable wrist strap",
      "Magnetic closure",
      "Compact yet spacious",
      "Unique artisan piece",
    ],
    specifications: [
      { label: "Material", value: "Natural Jute with Cotton Lining" },
      { label: "Dimensions", value: "10 x 6 x 2 inches" },
      { label: "Closure", value: "Magnetic Snap" },
      { label: "Strap", value: "Detachable Wrist Strap" },
      { label: "Embroidery", value: "Traditional Hand Embroidery" },
    ],
    careInstructions: [
      "Spot clean only",
      "Keep dry",
      "Store in dust bag when not in use",
      "Avoid overloading",
    ],
    material: "Natural Jute",
    color: "Natural with Multi-color Embroidery",
    inStock: true,
    stockCount: 42,
    sku: "HJC-CLT-011",
    brand: "Softzy",
    weight: "150g",
    dimensions: "10 x 6 x 2 inches",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/jute-clutch",
  },
  {
    id: "12",
    name: "Beaded Anklet Set",
    slug: "beaded-anklet-set",
    isMustTry: true,
    isTrending: true,
    price: 299.0,
    originalPrice: 449.0,
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.4,
    reviews: 92,
    tags: ["Sale"],
    category: "accessories",
    shortDescription:
      "Delicate beaded anklet set with charm details. Perfect for beach days and bohemian vibes.",
    description:
      "Add a touch of bohemian charm to your look with our Beaded Anklet Set. This beautiful set includes two complementary anklets featuring colorful glass beads, tiny charms, and adjustable closures. Perfect for beach vacations, festival season, or adding a free-spirited touch to your everyday style.\n\nThe anklets are designed to be layered together or worn separately for different looks. The adjustable chain ensures a comfortable fit for most ankle sizes, and the durable construction means these anklets will be your warm-weather staple for seasons to come.",
    features: [
      "Set of 2 complementary anklets",
      "Colorful glass beads",
      "Delicate charm details",
      "Adjustable length",
      "Durable construction",
      "Layer together or wear separately",
      "Perfect for beach and festival wear",
    ],
    specifications: [
      { label: "Material", value: "Alloy with Glass Beads" },
      { label: "Length", value: "8 inches with 2 inch extender" },
      { label: "Set Contains", value: "2 Anklets" },
      { label: "Closure", value: "Lobster Clasp" },
    ],
    careInstructions: [
      "Remove before swimming",
      "Avoid contact with lotions and perfumes",
      "Store in jewelry pouch",
      "Clean with soft dry cloth",
    ],
    material: "Alloy, Glass Beads",
    color: "Multi-color",
    inStock: true,
    stockCount: 78,
    sku: "BAS-ANK-012",
    brand: "Softzy",
    weight: "20g",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/beaded-anklet-set",
  },
];