import { Product } from "./productCard";

export const shopProducts: Product[] = [
  {
    id: "1",
    name: "Pyar Embroidered Straight Short Kurti",
    slug: "pyar-embroidered-straight-short-kurti",
    price: 950.0,
    originalPrice: 1299.0,
    images: [
      "https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviews: 124,
    tags: ["Best Seller", "New"],
    category: "clothing",
    shortDescription: "Elegant embroidered kurti perfect for casual and festive occasions. Made with premium cotton fabric for ultimate comfort.",
    description: "Introducing our stunning Pyar Embroidered Straight Short Kurti, a perfect blend of traditional craftsmanship and contemporary style. This beautiful kurti features intricate embroidery work that showcases the rich heritage of Indian textile artistry. The straight-cut silhouette offers a flattering fit for all body types, while the short length makes it versatile enough to pair with jeans, palazzos, or traditional bottoms.\n\nCrafted from premium quality cotton fabric, this kurti ensures breathability and comfort throughout the day. The soft texture feels gentle against the skin, making it ideal for long hours of wear. Whether you're heading to the office, attending a casual gathering, or celebrating a festive occasion, this kurti will keep you looking effortlessly elegant.",
    features: [
      "Hand-embroidered intricate patterns",
      "Premium 100% cotton fabric",
      "Comfortable straight-cut fit",
      "Versatile short length",
      "Easy to wash and maintain",
      "Fade-resistant colors",
      "Breathable fabric for all-day comfort"
    ],
    specifications: [
      { label: "Fabric", value: "100% Cotton" },
      { label: "Pattern", value: "Embroidered" },
      { label: "Sleeve Type", value: "3/4th Sleeves" },
      { label: "Neck Type", value: "Round Neck" },
      { label: "Hem Length", value: "Short/Hip Length" },
      { label: "Fit Type", value: "Regular Fit" },
      { label: "Occasion", value: "Casual, Festive, Office Wear" },
      { label: "Wash Care", value: "Machine Washable" }
    ],
    careInstructions: [
      "Machine wash cold with similar colors",
      "Do not bleach",
      "Tumble dry low",
      "Iron on medium heat",
      "Do not dry clean"
    ],
    material: "100% Premium Cotton",
    color: "Red with White Embroidery",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 45,
    sku: "PESS-KRT-001",
    brand: "Softzy",
    weight: "250g",
    dimensions: "Varies by size",
    warranty: "30-day quality guarantee",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/pyar-embroidered-kurti"
  },
  {
    id: "2",
    name: "Floral Print Cotton Anarkali Kurti",
    slug: "floral-print-cotton-anarkali-kurti",
    price: 1250.0,
    originalPrice: 1599.0,
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.6,
    reviews: 89,
    tags: ["Trending"],
    category: "clothing",
    shortDescription: "Beautiful floral print Anarkali kurti with a flowing silhouette. Perfect for festive occasions and celebrations.",
    description: "Step into elegance with our Floral Print Cotton Anarkali Kurti. This stunning piece features a gorgeous floral print that captures the essence of nature's beauty. The classic Anarkali silhouette flows gracefully, creating a regal and feminine look that's perfect for special occasions.\n\nMade from breathable cotton fabric, this kurti keeps you comfortable while looking absolutely stunning. The vibrant floral patterns are printed using eco-friendly dyes that are gentle on your skin and the environment.",
    features: [
      "Beautiful floral print design",
      "Classic Anarkali silhouette",
      "Breathable cotton fabric",
      "Eco-friendly dyes",
      "Elegant flared bottom",
      "Perfect for festive wear"
    ],
    specifications: [
      { label: "Fabric", value: "Cotton" },
      { label: "Pattern", value: "Floral Print" },
      { label: "Style", value: "Anarkali" },
      { label: "Sleeve Type", value: "Full Sleeves" },
      { label: "Occasion", value: "Festive, Party Wear" }
    ],
    careInstructions: [
      "Hand wash recommended",
      "Wash separately first time",
      "Do not bleach",
      "Dry in shade"
    ],
    material: "Cotton",
    color: "Multi-color Floral",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    stockCount: 32,
    sku: "FPC-ANK-002",
    brand: "Softzy",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/floral-anarkali"
  },
  {
    id: "3",
    name: "Designer Chikankari Kurti",
    slug: "designer-chikankari-kurti",
    price: 1450.0,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviews: 156,
    tags: ["New"],
    category: "clothing",
    shortDescription: "Authentic Lucknowi Chikankari hand-embroidered kurti. A masterpiece of traditional Indian craftsmanship.",
    description: "Experience the timeless elegance of Lucknowi Chikankari with our Designer Chikankari Kurti. Each piece is meticulously hand-embroidered by skilled artisans who have inherited this beautiful craft through generations. The delicate threadwork creates intricate patterns that are both subtle and stunning.\n\nThis kurti represents the finest traditions of Indian handloom industry. The lightweight fabric combined with the exquisite embroidery makes it perfect for both casual outings and formal occasions.",
    features: [
      "Authentic Lucknowi Chikankari",
      "100% hand-embroidered",
      "Lightweight and comfortable",
      "Artisan crafted",
      "Timeless design",
      "Premium quality fabric"
    ],
    specifications: [
      { label: "Fabric", value: "Cotton Cambric" },
      { label: "Embroidery", value: "Chikankari Hand Embroidery" },
      { label: "Origin", value: "Lucknow, India" },
      { label: "Craft Type", value: "Traditional Handloom" }
    ],
    material: "Cotton Cambric",
    color: "White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 18,
    sku: "DCK-CHK-003",
    brand: "Softzy",
    warranty: "Authenticity guaranteed",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/chikankari-kurti"
  },
  {
    id: "4",
    name: "Gold Plated Kundan Necklace Set",
    slug: "gold-plated-kundan-necklace-set",
    price: 2499.0,
    originalPrice: 3499.0,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviews: 203,
    tags: ["Best Seller"],
    category: "jewelry",
    shortDescription: "Exquisite gold-plated Kundan necklace set with matching earrings. Perfect for weddings and special occasions.",
    description: "Adorn yourself with the magnificence of our Gold Plated Kundan Necklace Set. This stunning jewelry set features authentic Kundan work, a traditional Indian jewelry-making technique that has been practiced for centuries. The intricate setting of polished glass stones creates a mesmerizing sparkle that catches light beautifully.\n\nThe set includes a statement necklace and matching earrings, creating a complete look for your special occasions. Whether it's a wedding, engagement, or festive celebration, this jewelry set will make you the center of attention.\n\nCrafted with high-quality materials and finished with premium gold plating, this set offers the luxurious look of fine jewelry at an accessible price point.",
    features: [
      "Authentic Kundan craftsmanship",
      "Premium gold plating",
      "Includes necklace and earrings",
      "Hypoallergenic materials",
      "Secure clasps",
      "Elegant presentation box included",
      "Suitable for sensitive skin"
    ],
    specifications: [
      { label: "Material", value: "Brass with Gold Plating" },
      { label: "Stone Type", value: "Kundan (Polished Glass)" },
      { label: "Plating", value: "22K Gold Plated" },
      { label: "Necklace Length", value: "18 inches with 2 inch extender" },
      { label: "Earring Type", value: "Jhumka Style" },
      { label: "Closure", value: "Lobster Clasp" },
      { label: "Set Includes", value: "1 Necklace, 1 Pair Earrings" }
    ],
    careInstructions: [
      "Store in jewelry box when not wearing",
      "Avoid contact with water and perfume",
      "Clean with soft dry cloth",
      "Remove before sleeping or bathing"
    ],
    material: "Brass with 22K Gold Plating",
    color: "Gold with Multi-color Stones",
    inStock: true,
    stockCount: 25,
    sku: "GPK-NKL-004",
    brand: "Softzy Jewels",
    weight: "85g",
    warranty: "6 months plating warranty",
    returnPolicy: "Easy 7-day returns (unworn items)",
    buyLink: "https://example.com/buy/kundan-necklace-set"
  },
  {
    id: "5",
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    price: 599.0,
    originalPrice: 899.0,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviews: 78,
    tags: ["Sale"],
    category: "jewelry",
    shortDescription: "Elegant pearl drop earrings that add a touch of sophistication to any outfit. Classic design for everyday luxury.",
    description: "Embrace timeless elegance with our Pearl Drop Earrings. These beautifully crafted earrings feature lustrous freshwater pearls that hang gracefully, catching the light with every movement. The classic drop design is both versatile and sophisticated, making these earrings perfect for any occasion.\n\nWhether you're dressing up for a formal event or adding a touch of refinement to your everyday look, these pearl earrings will become your go-to accessory. The high-quality sterling silver posts are hypoallergenic, ensuring comfortable wear even for sensitive ears.",
    features: [
      "Genuine freshwater pearls",
      "Sterling silver posts",
      "Hypoallergenic",
      "Lightweight and comfortable",
      "Versatile design",
      "Gift box included"
    ],
    specifications: [
      { label: "Pearl Type", value: "Freshwater Pearl" },
      { label: "Pearl Size", value: "8-9mm" },
      { label: "Post Material", value: "925 Sterling Silver" },
      { label: "Drop Length", value: "1.5 inches" },
      { label: "Backing Type", value: "Push Back" }
    ],
    careInstructions: [
      "Wipe with soft cloth after wearing",
      "Store separately from other jewelry",
      "Avoid contact with chemicals",
      "Put on after applying makeup and perfume"
    ],
    material: "Freshwater Pearl, Sterling Silver",
    color: "White Pearl / Silver",
    inStock: true,
    stockCount: 56,
    sku: "PDE-EAR-005",
    brand: "Softzy Jewels",
    weight: "8g",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/pearl-drop-earrings"
  },
  {
    id: "6",
    name: "Handcrafted Brass Diya Set",
    slug: "handcrafted-brass-diya-set",
    price: 899.0,
    images: [
      "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviews: 56,
    tags: ["Trending"],
    category: "home-decor",
    shortDescription: "Traditional handcrafted brass diya set for pooja and home decoration. Set of 5 beautiful diyas with intricate designs.",
    description: "Illuminate your home with divine radiance using our Handcrafted Brass Diya Set. This exquisite set of 5 diyas is lovingly handcrafted by skilled artisans using traditional techniques passed down through generations. Each diya features intricate engravings and patterns that reflect India's rich cultural heritage.\n\nPerfect for daily pooja, festivals like Diwali, or simply as decorative pieces, these brass diyas add warmth and spirituality to any space. The high-quality brass ensures durability and develops a beautiful patina over time, making each piece uniquely yours.\n\nThese diyas are not just functional items but works of art that celebrate the craftsmanship of Indian artisans.",
    features: [
      "100% handcrafted by skilled artisans",
      "Premium quality brass",
      "Set of 5 diyas in varying sizes",
      "Intricate traditional engravings",
      "Durable and long-lasting",
      "Develops beautiful patina over time",
      "Suitable for oil or ghee"
    ],
    specifications: [
      { label: "Material", value: "Pure Brass" },
      { label: "Set Contains", value: "5 Diyas" },
      { label: "Sizes", value: "2 inch, 2.5 inch, 3 inch, 3.5 inch, 4 inch" },
      { label: "Craft", value: "Hand Engraved" },
      { label: "Finish", value: "Antique Brass" },
      { label: "Weight (Total)", value: "450g" }
    ],
    careInstructions: [
      "Clean with brass cleaner or lemon and salt",
      "Wipe dry after cleaning",
      "Store in dry place",
      "Handle with care to preserve engravings"
    ],
    material: "Pure Brass",
    color: "Antique Brass",
    inStock: true,
    stockCount: 38,
    sku: "HBD-SET-006",
    brand: "Softzy Home",
    weight: "450g",
    dimensions: "Various sizes (2-4 inch diameter)",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/brass-diya-set"
  },
  {
    id: "7",
    name: "Macrame Wall Hanging",
    slug: "macrame-wall-hanging",
    price: 1299.0,
    images: [
      "https://images.unsplash.com/photo-1622837137217-a5af75b81ed0?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.6,
    reviews: 34,
    tags: ["New"],
    category: "home-decor",
    shortDescription: "Beautiful handmade macrame wall hanging. Adds bohemian charm and texture to any room.",
    description: "Transform your walls with our stunning Macrame Wall Hanging. This beautiful piece is entirely handcrafted using the ancient art of macrame, where cords are knotted together to create intricate patterns. Each wall hanging is a unique work of art, made with love and attention to detail.\n\nThe bohemian-inspired design adds texture, warmth, and visual interest to any space. Whether hung in your living room, bedroom, or even outdoors, this macrame piece creates a focal point that guests will admire.\n\nMade from 100% natural cotton cord, this wall hanging is eco-friendly and sustainable, aligning with conscious living values.",
    features: [
      "100% handmade macrame",
      "Natural cotton cord",
      "Bohemian design",
      "Easy to hang",
      "Eco-friendly materials",
      "Unique artisan piece",
      "Includes wooden dowel"
    ],
    specifications: [
      { label: "Material", value: "100% Cotton Cord" },
      { label: "Dimensions", value: "24 inches wide x 36 inches long" },
      { label: "Hanging Method", value: "Wooden Dowel" },
      { label: "Style", value: "Bohemian / Boho" },
      { label: "Color", value: "Natural Cream" }
    ],
    careInstructions: [
      "Dust gently with soft brush",
      "Spot clean if necessary",
      "Keep away from direct sunlight to prevent yellowing",
      "Reshape tassels gently if needed"
    ],
    material: "100% Natural Cotton",
    color: "Natural Cream",
    inStock: true,
    stockCount: 22,
    sku: "MWH-DEC-007",
    brand: "Softzy Home",
    weight: "350g",
    dimensions: "24 x 36 inches",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/macrame-wall-hanging"
  },
  {
    id: "8",
    name: "Organic Rose Face Serum",
    slug: "organic-rose-face-serum",
    price: 649.0,
    originalPrice: 899.0,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviews: 203,
    tags: ["Best Seller"],
    category: "beauty",
    shortDescription: "Luxurious organic face serum with pure rose extracts. Hydrates, nourishes, and gives you a natural glow.",
    description: "Reveal your skin's natural radiance with our Organic Rose Face Serum. This luxurious serum is crafted with pure rose extracts and a blend of organic botanical oils that work together to deeply nourish and hydrate your skin. The lightweight formula absorbs quickly, leaving your skin soft, supple, and glowing.\n\nRoses have been celebrated for centuries for their skincare benefits, and our serum captures these benefits in every drop. Rich in antioxidants and vitamins, this serum helps combat signs of aging while providing intense hydration.\n\nFree from harsh chemicals, parabens, and artificial fragrances, this serum is gentle enough for all skin types, including sensitive skin.",
    features: [
      "100% organic ingredients",
      "Pure rose extract",
      "Lightweight, fast-absorbing",
      "Suitable for all skin types",
      "Paraben-free and cruelty-free",
      "No artificial fragrances",
      "Antioxidant-rich formula",
      "Visible results in 2 weeks"
    ],
    specifications: [
      { label: "Volume", value: "30ml" },
      { label: "Key Ingredients", value: "Rose Extract, Rosehip Oil, Vitamin E" },
      { label: "Skin Type", value: "All Skin Types" },
      { label: "Texture", value: "Lightweight Serum" },
      { label: "Certification", value: "Organic Certified" },
      { label: "Shelf Life", value: "24 months (unopened)" }
    ],
    careInstructions: [
      "Apply 2-3 drops on clean, damp skin",
      "Use morning and night for best results",
      "Follow with moisturizer",
      "Store in cool, dry place away from sunlight"
    ],
    material: "Organic Rose Extract, Natural Oils",
    inStock: true,
    stockCount: 89,
    sku: "ORF-SER-008",
    brand: "Softzy Beauty",
    weight: "50g (with packaging)",
    warranty: "Satisfaction guaranteed",
    returnPolicy: "Unopened items returnable within 7 days",
    buyLink: "https://example.com/buy/rose-face-serum"
  },
  {
    id: "9",
    name: "Ayurvedic Hair Oil",
    slug: "ayurvedic-hair-oil",
    price: 449.0,
    originalPrice: 599.0,
    images: [
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviews: 167,
    tags: ["Sale"],
    category: "beauty",
    shortDescription: "Traditional Ayurvedic hair oil with 21 herbs. Promotes hair growth, reduces hair fall, and nourishes scalp.",
    description: "Revitalize your hair with our traditional Ayurvedic Hair Oil, formulated with a powerful blend of 21 herbs known for their hair-nourishing properties. This time-tested formula combines ancient Ayurvedic wisdom with modern quality standards to deliver an oil that truly transforms your hair.\n\nThe carefully selected herbs including Bhringraj, Amla, Brahmi, and Coconut Oil work synergistically to strengthen hair roots, reduce hair fall, promote new hair growth, and add natural shine. Regular use helps address common hair concerns while keeping your scalp healthy.\n\nOur oil is cold-pressed to preserve the natural nutrients and is free from mineral oils, parabens, and artificial additives.",
    features: [
      "21 Ayurvedic herbs blend",
      "Promotes hair growth",
      "Reduces hair fall",
      "Nourishes scalp",
      "Cold-pressed extraction",
      "No mineral oil or parabens",
      "Traditional formulation",
      "Pleasant herbal fragrance"
    ],
    specifications: [
      { label: "Volume", value: "200ml" },
      { label: "Key Herbs", value: "Bhringraj, Amla, Brahmi, Coconut Oil" },
      { label: "Hair Type", value: "All Hair Types" },
      { label: "Extraction", value: "Cold Pressed" },
      { label: "Shelf Life", value: "36 months" }
    ],
    careInstructions: [
      "Massage gently into scalp and hair",
      "Leave for at least 1 hour or overnight",
      "Wash with mild shampoo",
      "Use 2-3 times per week for best results"
    ],
    material: "Natural Ayurvedic Herbs & Oils",
    inStock: true,
    stockCount: 134,
    sku: "AYU-OIL-009",
    brand: "Softzy Beauty",
    weight: "220g",
    returnPolicy: "Unopened items returnable within 7 days",
    buyLink: "https://example.com/buy/ayurvedic-hair-oil"
  },
  {
    id: "10",
    name: "Leather Tote Bag",
    slug: "leather-tote-bag",
    price: 1999.0,
    originalPrice: 2799.0,
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviews: 67,
    tags: ["Trending"],
    category: "bags",
    shortDescription: "Premium leather tote bag with spacious interior. Perfect for work, travel, or everyday use.",
    description: "Elevate your everyday style with our Premium Leather Tote Bag. Crafted from genuine full-grain leather, this tote combines timeless elegance with practical functionality. The spacious interior easily accommodates your laptop, documents, and daily essentials, making it perfect for the modern professional.\n\nThe bag features multiple interior pockets for organization, reinforced stitching for durability, and comfortable leather handles that soften with use. The leather develops a beautiful patina over time, making each bag uniquely yours.\n\nWhether you're heading to the office, traveling, or running errands, this versatile tote bag transitions seamlessly from professional to casual settings.",
    features: [
      "Genuine full-grain leather",
      "Spacious main compartment",
      "Fits 15-inch laptop",
      "Multiple interior pockets",
      "Reinforced stitching",
      "Magnetic snap closure",
      "Comfortable carry handles",
      "Develops patina over time"
    ],
    specifications: [
      { label: "Material", value: "Full-Grain Leather" },
      { label: "Dimensions", value: "16 x 12 x 5 inches" },
      { label: "Strap Drop", value: "10 inches" },
      { label: "Closure", value: "Magnetic Snap" },
      { label: "Interior", value: "Cotton Lining" },
      { label: "Pockets", value: "2 Interior, 1 Zipper" }
    ],
    careInstructions: [
      "Wipe with damp cloth for regular cleaning",
      "Use leather conditioner every 3-6 months",
      "Store stuffed to maintain shape",
      "Keep away from direct heat and sunlight"
    ],
    material: "Full-Grain Leather",
    color: "Tan Brown",
    inStock: true,
    stockCount: 28,
    sku: "LTB-BAG-010",
    brand: "Softzy",
    weight: "850g",
    dimensions: "16 x 12 x 5 inches",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/leather-tote-bag"
  },
  {
    id: "11",
    name: "Handmade Jute Clutch",
    slug: "handmade-jute-clutch",
    price: 499.0,
    images: [
      "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.3,
    reviews: 45,
    tags: ["New"],
    category: "bags",
    shortDescription: "Eco-friendly handmade jute clutch with traditional embroidery. Sustainable fashion at its best.",
    description: "Make a sustainable style statement with our Handmade Jute Clutch. This eco-friendly clutch is crafted from natural jute fiber and adorned with beautiful traditional embroidery, showcasing the skill of Indian artisans. The perfect blend of sustainability and style, this clutch proves that fashion can be both beautiful and responsible.\n\nThe compact size is ideal for carrying your essentials – phone, cards, keys, and makeup touch-ups. The secure magnetic closure keeps your belongings safe, while the detachable wrist strap offers versatile carrying options.\n\nEach clutch is unique, with slight variations in embroidery that make it truly one-of-a-kind.",
    features: [
      "100% natural jute fiber",
      "Handmade with traditional embroidery",
      "Eco-friendly and sustainable",
      "Detachable wrist strap",
      "Magnetic closure",
      "Compact yet spacious",
      "Unique artisan piece"
    ],
    specifications: [
      { label: "Material", value: "Natural Jute with Cotton Lining" },
      { label: "Dimensions", value: "10 x 6 x 2 inches" },
      { label: "Closure", value: "Magnetic Snap" },
      { label: "Strap", value: "Detachable Wrist Strap" },
      { label: "Embroidery", value: "Traditional Hand Embroidery" }
    ],
    careInstructions: [
      "Spot clean only",
      "Keep dry",
      "Store in dust bag when not in use",
      "Avoid overloading"
    ],
    material: "Natural Jute",
    color: "Natural with Multi-color Embroidery",
    inStock: true,
    stockCount: 42,
    sku: "HJC-CLT-011",
    brand: "Softzy",
    weight: "150g",
    dimensions: "10 x 6 x 2 inches",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/jute-clutch"
  },
  {
    id: "12",
    name: "Beaded Anklet Set",
    slug: "beaded-anklet-set",
    price: 299.0,
    originalPrice: 449.0,
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.4,
    reviews: 92,
    tags: ["Sale"],
    category: "accessories",
    shortDescription: "Delicate beaded anklet set with charm details. Perfect for beach days and bohemian vibes.",
    description: "Add a touch of bohemian charm to your look with our Beaded Anklet Set. This beautiful set includes two complementary anklets featuring colorful glass beads, tiny charms, and adjustable closures. Perfect for beach vacations, festival season, or adding a free-spirited touch to your everyday style.\n\nThe anklets are designed to be layered together or worn separately for different looks. The adjustable chain ensures a comfortable fit for most ankle sizes, and the durable construction means these anklets will be your warm-weather staple for seasons to come.",
    features: [
      "Set of 2 complementary anklets",
      "Colorful glass beads",
      "Delicate charm details",
      "Adjustable length",
      "Durable construction",
      "Layer together or wear separately",
      "Perfect for beach and festival wear"
    ],
    specifications: [
      { label: "Material", value: "Alloy with Glass Beads" },
      { label: "Length", value: "8 inches with 2 inch extender" },
      { label: "Set Contains", value: "2 Anklets" },
      { label: "Closure", value: "Lobster Clasp" }
    ],
    careInstructions: [
      "Remove before swimming",
      "Avoid contact with lotions and perfumes",
      "Store in jewelry pouch",
      "Clean with soft dry cloth"
    ],
    material: "Alloy, Glass Beads",
    color: "Multi-color",
    inStock: true,
    stockCount: 78,
    sku: "BAS-ANK-012",
    brand: "Softzy",
    weight: "20g",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/beaded-anklet-set"
  },
  {
    id: "13",
    name: "Silk Scarf Collection",
    slug: "silk-scarf-collection",
    price: 799.0,
    images: [
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.6,
    reviews: 78,
    tags: ["Trending", "New"],
    category: "accessories",
    shortDescription: "Luxurious pure silk scarf with artistic print. Versatile accessory for endless styling possibilities.",
    description: "Wrap yourself in luxury with our Pure Silk Scarf. This exquisite scarf is crafted from 100% mulberry silk, known for its incredible softness and lustrous sheen. The beautiful artistic print adds a pop of color and sophistication to any outfit.\n\nThe versatility of this scarf knows no bounds – wear it around your neck, tie it to your handbag, use it as a headband, or even frame it as art. The generous size allows for multiple styling options, making it a must-have accessory for the fashion-forward individual.\n\nSilk is naturally hypoallergenic and temperature-regulating, making this scarf comfortable to wear in any season.",
    features: [
      "100% pure mulberry silk",
      "Artistic designer print",
      "Hand-rolled edges",
      "Versatile styling options",
      "Hypoallergenic",
      "Temperature regulating",
      "Comes in silk pouch"
    ],
    specifications: [
      { label: "Material", value: "100% Mulberry Silk" },
      { label: "Dimensions", value: "35 x 35 inches" },
      { label: "Weight", value: "65g" },
      { label: "Print", value: "Digital Print" },
      { label: "Edge Finish", value: "Hand-rolled" }
    ],
    careInstructions: [
      "Dry clean recommended",
      "Can be hand washed in cold water",
      "Use mild silk detergent",
      "Do not wring – roll in towel to dry",
      "Iron on low heat while slightly damp"
    ],
    material: "100% Mulberry Silk",
    color: "Multi-color Print",
    inStock: true,
    stockCount: 35,
    sku: "SSC-SCF-013",
    brand: "Softzy",
    weight: "65g",
    dimensions: "35 x 35 inches",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/silk-scarf"
  },
  {
    id: "14",
    name: "Embroidered Mojari",
    slug: "embroidered-mojari",
    price: 1199.0,
    images: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviews: 134,
    tags: ["Best Seller"],
    category: "footwear",
    shortDescription: "Traditional handcrafted Mojari with intricate embroidery. Comfortable flat footwear for ethnic occasions.",
    description: "Step into tradition with our Embroidered Mojari, a celebration of India's rich footwear heritage. These handcrafted shoes feature intricate embroidery work that showcases the exceptional skill of Rajasthani artisans. The vibrant colors and detailed patterns make each pair a wearable work of art.\n\nDesigned for comfort, these mojaris feature a cushioned insole and flexible sole that make them ideal for all-day wear. Whether you're attending a wedding, festival, or simply want to add ethnic flair to your outfit, these mojaris are the perfect choice.\n\nThe genuine leather construction ensures durability while allowing your feet to breathe, keeping you comfortable in warm weather.",
    features: [
      "Handcrafted by skilled artisans",
      "Intricate traditional embroidery",
      "Genuine leather construction",
      "Cushioned insole",
      "Flexible rubber sole",
      "Breathable design",
      "Perfect for ethnic occasions"
    ],
    specifications: [
      { label: "Upper Material", value: "Genuine Leather with Embroidery" },
      { label: "Sole", value: "Flexible Rubber" },
      { label: "Insole", value: "Cushioned Leather" },
      { label: "Heel Height", value: "Flat (0.5 inch)" },
      { label: "Craft", value: "Rajasthani Hand Embroidery" },
      { label: "Available Sizes", value: "5 to 11 (Indian)" }
    ],
    careInstructions: [
      "Wipe with damp cloth to clean",
      "Use leather polish occasionally",
      "Store away from direct sunlight",
      "Use shoe trees to maintain shape"
    ],
    material: "Genuine Leather",
    color: "Multi-color Embroidery",
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    inStock: true,
    stockCount: 45,
    sku: "EMB-MOJ-014",
    brand: "Softzy",
    weight: "300g (per pair)",
    returnPolicy: "Easy 7-day returns (unworn items)",
    buyLink: "https://example.com/buy/embroidered-mojari"
  },
  {
    id: "15",
    name: "Kolhapuri Chappal",
    slug: "kolhapuri-chappal",
    price: 899.0,
    images: [
      "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviews: 89,
    tags: ["Trending"],
    category: "footwear",
    shortDescription: "Authentic handmade Kolhapuri chappal. Traditional craftsmanship meets timeless style.",
    description: "Experience authentic Indian craftsmanship with our Kolhapuri Chappal. Originating from the town of Kolhapur in Maharashtra, these iconic sandals have been a staple of Indian footwear for centuries. Each pair is handmade by skilled cobblers using traditional techniques that have been passed down through generations.\n\nThe distinctive T-strap design and hand-tooled leather upper make these sandals instantly recognizable. Made from vegetable-tanned leather, these chappals are durable, eco-friendly, and become more comfortable with each wear as they mold to your feet.\n\nPerfect for ethnic wear and casual outfits alike, Kolhapuri chappals add a touch of traditional charm to any ensemble.",
    features: [
      "Authentic Kolhapuri craftsmanship",
      "100% genuine leather",
      "Vegetable tanned (eco-friendly)",
      "Hand-tooled designs",
      "Durable construction",
      "Molds to feet for custom fit",
      "Traditional T-strap design"
    ],
    specifications: [
      { label: "Material", value: "Vegetable Tanned Leather" },
      { label: "Sole", value: "Leather with Rubber Grip" },
      { label: "Design", value: "Traditional T-Strap" },
      { label: "Origin", value: "Kolhapur, Maharashtra" },
      { label: "Available Sizes", value: "5 to 11 (Indian)" }
    ],
    careInstructions: [
      "Apply leather cream for maintenance",
      "Keep dry – avoid water exposure",
      "Store in ventilated area",
      "Break in gradually for best comfort"
    ],
    material: "Genuine Vegetable Tanned Leather",
    color: "Tan Brown",
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    inStock: true,
    stockCount: 52,
    sku: "KOL-CHP-015",
    brand: "Softzy",
    weight: "350g (per pair)",
    returnPolicy: "Easy 7-day returns (unworn items)",
    buyLink: "https://example.com/buy/kolhapuri-chappal"
  },
  {
    id: "16",
    name: "Temple Jewelry Set",
    slug: "temple-jewelry-set",
    price: 5499.0,
    originalPrice: 7999.0,
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviews: 112,
    tags: ["Featured", "Best Seller"],
    category: "jewelry",
    shortDescription: "Magnificent temple jewelry complete set. Includes necklace, earrings, tikka, and bangles for the perfect bridal look.",
    description: "Adorn yourself like royalty with our exquisite Temple Jewelry Set. This magnificent collection draws inspiration from the ornate jewelry adorning deities in South Indian temples, featuring intricate designs that have captivated hearts for centuries. This complete set includes everything you need for a stunning bridal or festive look.\n\nEach piece is crafted with meticulous attention to detail, featuring traditional motifs like peacocks, goddesses, and floral patterns. The gold-plated finish provides a luxurious appearance, while the carefully set stones add sparkle and dimension.\n\nThis set is perfect for weddings, Bharatanatyam performances, or any occasion where you want to make a grand statement. The timeless designs ensure that this jewelry set will be treasured for generations.",
    features: [
      "Complete temple jewelry set",
      "Includes necklace, earrings, tikka, and bangles",
      "Traditional South Indian design",
      "Premium gold plating",
      "Intricate deity and peacock motifs",
      "Hypoallergenic materials",
      "Comes in luxury presentation box",
      "Perfect for bridal and festive occasions"
    ],
    specifications: [
      { label: "Material", value: "Brass with 22K Gold Plating" },
      { label: "Stone Type", value: "Ruby, Emerald (Imitation)" },
      { label: "Set Includes", value: "Necklace, Earrings, Tikka, 2 Bangles" },
      { label: "Necklace Length", value: "20 inches with extender" },
      { label: "Earring Style", value: "Jhumka" },
      { label: "Bangle Size", value: "2.4, 2.6, 2.8 available" },
      { label: "Total Weight", value: "280g" }
    ],
    careInstructions: [
      "Store in provided jewelry box",
      "Avoid contact with water, perfume, and chemicals",
      "Clean gently with soft dry cloth",
      "Keep away from humidity"
    ],
    material: "Brass with 22K Gold Plating",
    color: "Gold with Ruby & Emerald",
    sizes: ["2.4", "2.6", "2.8"],
    inStock: true,
    stockCount: 12,
    sku: "TJS-SET-016",
    brand: "Softzy Jewels",
    weight: "280g",
    warranty: "1 year plating warranty",
    returnPolicy: "Easy 7-day returns (unworn items)",
    buyLink: "https://example.com/buy/temple-jewelry-set"
  },
  {
    id: "17",
    name: "Cotton Block Print Dupatta",
    slug: "cotton-block-print-dupatta",
    price: 450.0,
    originalPrice: 650.0,
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.3,
    reviews: 56,
    tags: ["Sale"],
    category: "accessories",
    shortDescription: "Beautiful hand block printed cotton dupatta. Traditional Jaipur craft with modern appeal.",
    description: "Add a pop of color and tradition to your outfit with our Cotton Block Print Dupatta. This beautiful dupatta showcases the ancient art of hand block printing, a traditional craft practiced in the vibrant city of Jaipur. Skilled artisans carve intricate patterns into wooden blocks and stamp them by hand onto the fabric, creating unique prints with subtle variations that make each piece one-of-a-kind.\n\nMade from soft, breathable cotton, this dupatta is perfect for all seasons. The generous size allows for multiple draping styles, making it a versatile addition to your ethnic wardrobe.\n\nThe natural dyes used in our block prints are eco-friendly and gentle on the skin, making this dupatta a sustainable fashion choice.",
    features: [
      "Authentic hand block print",
      "100% cotton fabric",
      "Natural vegetable dyes",
      "Generous size for versatile draping",
      "Traditional Jaipur craft",
      "Eco-friendly production",
      "Each piece is unique"
    ],
    specifications: [
      { label: "Material", value: "100% Cotton" },
      { label: "Dimensions", value: "2.5 meters x 1 meter" },
      { label: "Print Type", value: "Hand Block Print" },
      { label: "Dye", value: "Natural Vegetable Dyes" },
      { label: "Origin", value: "Jaipur, Rajasthan" }
    ],
    careInstructions: [
      "Hand wash separately in cold water",
      "Use mild detergent",
      "Do not bleach",
      "Dry in shade",
      "Iron on medium heat"
    ],
    material: "100% Cotton",
    color: "Multi-color Block Print",
    inStock: true,
    stockCount: 67,
    sku: "CBP-DUP-017",
    brand: "Softzy",
    weight: "180g",
    dimensions: "2.5m x 1m",
    returnPolicy: "Easy 7-day returns",
    buyLink: "https://example.com/buy/block-print-dupatta"
  },
  {
    id: "18",
    name: "Ceramic Planter Set",
    slug: "ceramic-planter-set",
    price: 1599.0,
    images: [
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviews: 43,
    tags: ["New"],
    category: "home-decor",
    shortDescription: "Handcrafted ceramic planter set of 3. Beautiful patterns to bring life to your indoor garden.",
    description: "Transform your indoor garden with our Handcrafted Ceramic Planter Set. This beautiful set of three planters is handmade by skilled potters using traditional techniques. Each planter features unique hand-painted patterns that add artistic flair to your plants and living spaces.\n\nThe planters come in three complementary sizes, perfect for creating an eye-catching display. Whether you're housing succulents, herbs, or small houseplants, these planters provide the perfect home. The drainage holes at the bottom ensure proper water management for healthy plants.\n\nCeramic planters are excellent for plant health as they allow air and moisture to pass through, preventing root rot and promoting healthy growth.",
    features: [
      "Set of 3 handcrafted planters",
      "Hand-painted unique patterns",
      "Drainage holes included",
      "Breathable ceramic material",
      "Three complementary sizes",
      "Comes with matching saucers",
      "Indoor and covered outdoor use"
    ],
    specifications: [
      { label: "Material", value: "Handcrafted Ceramic" },
      { label: "Set Contains", value: "3 Planters with Saucers" },
      { label: "Sizes", value: "4 inch, 5 inch, 6 inch (diameter)" },
      { label: "Drainage", value: "Yes, with holes" },
      { label: "Finish", value: "Matte with Hand-painted Design" }
    ],
    careInstructions: [
      "Wipe with damp cloth to clean",
      "Do not put in microwave or dishwasher",
      "Handle with care – ceramic is fragile",
      "Protect surface from moisture with saucer"
    ],
    material: "Handcrafted Ceramic",
    color: "Multi-pattern (Blue, Green, Terracotta)",
    inStock: true,
    stockCount: 29,
    sku: "CPS-DEC-018",
    brand: "Softzy Home",
    weight: "1.2kg (total set)",
    dimensions: "4, 5, 6 inch diameter",
    returnPolicy: "Easy 7-day returns (unbroken items)",
    buyLink: "https://example.com/buy/ceramic-planter-set"
  },
];